-- MySQL Script generated by MySQL Workbench
-- Mon Jul 30 11:10:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema meeting_ticket
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `meeting_ticket` ;

-- -----------------------------------------------------
-- Schema meeting_ticket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `meeting_ticket` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `timestamps` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);

SHOW WARNINGS;
USE `meeting_ticket` ;

-- -----------------------------------------------------
-- Table `meeting_ticket_meet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meeting_ticket_meet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `meeting_ticket_meet` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `title` VARCHAR(255) NOT NULL COMMENT '会议主题',
  `img_url` VARCHAR(255) NULL DEFAULT NULL COMMENT '主题图',
  `publisher` VARCHAR(100) NULL DEFAULT NULL COMMENT '发布者',
  `time` VARCHAR(100) NOT NULL COMMENT '时间',
  `ticket_price` VARCHAR(255) NULL DEFAULT NULL COMMENT '票价',
  `addr` VARCHAR(255) NOT NULL COMMENT '地址',
  `summary` MEDIUMTEXT NOT NULL COMMENT '简介',
  `content` MEDIUMTEXT NULL DEFAULT NULL COMMENT '具体内容：会议日程、主题简介（先主题后嘉宾）',
  `category_id` INT(11) NULL DEFAULT NULL,
  `guest` VARCHAR(255) NOT NULL COMMENT '嘉宾',
  `comment_id` INT(11) NULL DEFAULT NULL COMMENT '评论标识，用于关联评论表',
  `comment` INT(11) NULL DEFAULT NULL COMMENT '评论数',
  `collection` INT(11) NULL DEFAULT NULL COMMENT '收藏数',
  `sponsor` VARCHAR(200) NOT NULL COMMENT '主办方',
  `co_sponsor` VARCHAR(200) NULL DEFAULT NULL COMMENT '协办方',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `meeting_ticket_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meeting_ticket_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `meeting_ticket_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `age` INT(11) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  `permission` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `meeting_ticket_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meeting_ticket_category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `meeting_ticket_category` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(60) NOT NULL COMMENT '类别名称',
  `type` INT NULL DEFAULT 0 COMMENT '类型值',
  `create_time` VARCHAR(45) NULL COMMENT '创建时间',
  `last_update_time` VARCHAR(45) NULL COMMENT '最近更新时间',
  `position` TINYINT NULL DEFAULT 0 COMMENT '放置位置（比如置顶等）',
  `is_hot` TINYINT NULL DEFAULT 0 COMMENT '是否热门',
  `is_draft` TINYINT NULL DEFAULT 1 COMMENT '是否为草稿，待发布',
  `is_expired` TINYINT NULL DEFAULT 0 COMMENT '是否过期',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
